### ISSUE TITLE
Large theme differences between 2.0.x and 2.1.x

### ISSUE THREAD

**Issue by bestguy** [marcelo-mason/vscode-one-monokai#3]
I loved using this theme up to version 2.0.x, but the recent updates in past few days to 2.1.x change the colors a lot, it's basically a different theme from in my opinion.  Could you consider reverting these changes and releasing under a different name, or releasing the old theme separately?  Thanks for the work on this theme.

Before 2.1:
<img width="1431" alt="old" src="https://user-images.githubusercontent.com/405608/219908155-39c05766-825b-40ca-ab81-3afa7b00cbff.png">

After 2.1:
<img width="1440" alt="new" src="https://user-images.githubusercontent.com/405608/219908159-2931267c-e2d3-445e-b153-96811cf8259a.png">

**Comment by bestguy** [comment]
A workaround for others is you can right click the the theme in your extensions, and install older version:

<img width="442" alt="Screenshot 2023-02-18 at 6 04 56 PM" src="https://user-images.githubusercontent.com/405608/219908220-991c4250-581f-4f8e-a209-1981c2145f30.png">

Version 2.0.9 is the latest version that uses older theme colors.

**Comment by marcelo-mason** [comment]
Hear you, rolling it back and creating new theme for new UI color scheme.

**Comment by marcelo-mason** [comment]
"OneMonokai80s Original" now comes bundled as option on newer versions
