### ISSUE TITLE
changing selection colors doesn't work

### ISSUE THREAD

**Issue by elesq** [marcelo-mason/vscode-one-monokai#4]
Installing into VSC and limiting other plugins activated/installed to eliminate leaves the following issue still present: 

changing the selection colour background/foreground doesn't work in python.  It makes the theme difficult to work with overall as selections are not highlighted and this makes editor changes on selected items a frustrating experience. 

repo steps: 
1. install theme and set as selected theme
2. open a python script (also note that conda vs a pyenv env makes no difference)
3. select some items in the file, commented or code makes no difference. The highlighted color is indistinguishable 
4. make changes in the vsc settings files for editor.selection, selectionBackground, selectionHighlightBackground etc etc... 
5. verify the overrides prescribed don't apply to actively selected words.
6. switch to a different theme to check own sanity
7. make overrides changes once again
8. verify they do work as expected
9. write up issue on github repo

**Comment by marcelo-mason** [comment]
fixed in 2.2.3
