### ISSUE TITLE
Lack of contrast for deemphasized files and folders

### ISSUE THREAD

**Issue by mabeyrou** [marcelo-mason/vscode-one-monokai#5]
This theme is my favorite and day to day choice. Nevertheless, the lack of contrast for deemphasized files and folders is an issue for me. It makes it unreadable for me.
![folder_tab](https://github.com/marcelo-mason/one-monokai-80s/assets/73880465/3981962c-fc09-483b-915d-b6dbfe4414ff)
![node_modules](https://github.com/marcelo-mason/one-monokai-80s/assets/73880465/eb8b836c-cf51-4bf7-962d-4987de02bfae)

I would like to customize it but cannot find the proper property to override from the official [color theme guide](https://code.visualstudio.com/api/references/theme-color). I would have thought the `list.deemphasizedForeground` would do the trick but no... 

Would you know what property to override?

Thank you in advance and great job for this theme.

**Comment by marcelo-mason** [comment]
fixed in 2.2.2

**Comment by mabeyrou** [comment]
Thanks a lot for taking it into account :+1:
